FROM osrf/ros:kinetic-desktop-xenial

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get -y install \
    apt-utils \
    apt-transport-https \
    debconf-utils \
    git \
    wget \
    sudo
